#!/usr/bin/env bash

dunstapparmor() {
    while true; do
	ps aux | grep 'sleep 150' | awk '{print $2}' | xargs kill
	ps aux | grep 'sleep 6000' | awk '{print $2}' | xargs kill
	dunstctl rule apparmor-display-skip disable
	sleep 150
	dunstctl rule apparmor-display disable
	dunstctl rule apparmor-display-skip enable
	dunstify 'apparmor notification for firefox temporary disabled'
	sleep 6000
	dunstctl rule apparmor-display-skip disable
	dunstctl rule apparmor-display enable
	dunstify 'apparmor notification for firefox enabled'
    done
}

# configure X
xset -b
xset r rate 400 60
xhost -

sleep 1

setxkbmap -layout us,ua
setxkbmap -option grp:alt_shift_toggle

killall pulseaudio
killall /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
killall nitrogen
killall nm-applet
killall xfce4-power-manager
killall unclutter
killall udev-notify
killall psi-notify
killall caffeine
killall hushboard
killall autotiling
killall flashfocus
killall opensnitch-ui
killall redshift
killall pasystray
killall picom
killall pa-applet
killall dunst

sleep 1

# start userspace environmet utils

DISPLAY=:%i emacs --fg-daemon &

terminaldaemoncount=`pgrep urxvtd | wc -l` 

#if [ $terminaldaemoncount == 1 ]; then
#    notify-send "terminal daemon is already running"
#else
#    killall urxvtd
#    urxvtd -q -f -o &
#    notify-send "terminal daemon is started"
#fi

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore
nm-applet &
xfce4-power-manager &
unclutter &
udev-notify &
psi-notify &
caffeine &
hushboard &
autotiling &
flashfocus &
opensnitch-ui &
pa-applet &
pasystray &
firejail-telegram &
firejail-liferea &
picom -b

notify-send "skxkb, flameshot, pasystray, picom is started"

# killall dunst; dunst &

# dunstapparmor &

# firejail --noroot --apparmor --seccomp --name=clipit /usr/bin/clipit &

sleep 1

notify-send "hello ${USER} -_-
	    start redshift and apparmor parcer"

# start apparmor parces

redshift -t 6000:5000 -l 49.9627:33.6053 &

aa-notify -p -l -w 60 -f /var/log/audit/audit.log &
