#!/usr/bin/env bash

# configure X
xset -b
xset r rate 400 60
# xrandr --output eDP-1 --set TearFree on
xhost -

sleep 1

setxkbmap -layout us,ru,ua
setxkbmap -option grp:alt_shift_toggle

sleep 1 && redshift -t 6000:5000 -l 49.9627:33.6053 &

# firejail --noroot --apparmor --seccomp --name=clipit /usr/bin/clipit &

# sleep 1 && aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log & 

# sleep ss -lpntu
