#!/usr/bin/env bash

# configure X
xset -b
xset r rate 400 60
xhost -

sleep 1

setxkbmap -layout us,ru,ua
setxkbmap -option grp:alt_shift_toggle

killall redshift

sleep 1

# start userspace environmet utils

redshift -t 6000:5000 -l 49.9627:33.6053 -- &

DISPLAY=:%i emacs --fg-daemon -- &

urxvtd -q -o &

firejail --noroot --apparmor --seccomp --name=clipit /usr/bin/clipit -- &

sleep 1

# start apparmor parces

aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log &
