#!/usr/bin/env bash

dunstapparmor() {

    dunstctl rule apparmor-display-skip disable
    sleep 120
    dunstctl rule apparmor-display disable
    dunstctl rule apparmor-display-skip enable
    dunstify 'AppArmor notification for Firefox temporary disabled'
    sleep 6000
    dunstctl rule apparmor-display-skip disable
    dunstctl rule apparmor-display enable
    dunstify 'AppArmor notification for Firefox enabled'

}

# configure X
xset -b
xset r rate 400 60
xhost -

sleep 1

setxkbmap -layout us,ru,ua
setxkbmap -option grp:alt_shift_toggle

killall redshift

sleep 1

# start userspace environmet utils

DISPLAY=:%i emacs --fg-daemon -- &

terminaldaemoncount=`pgrep urxvtd | wc -l` 

if [ $terminaldaemoncount == 1 ]; then
    notify-send "Terminal daemon is started"
else
    killall urxvtd
    urxvtd -q -o &
fi

sleep 1

killall dunst; LD_PRELOAD="/usr/lib/libhardened_malloc.so" dunst -- &

dunstapparmor() &

# firejail --noroot --apparmor --seccomp --name=clipit /usr/bin/clipit -- -- &

sleep 1

notify-send "Hello ${USER} - Start Redshift and AppArmor parcer"

# start apparmor parces

redshift -t 6000:5000 -l 49.9627:33.6053 -- &

aa-notify -p -l -w 60 -f /var/log/audit/audit.log &
