#!/usr/bin/env bash

firejail --noprofile --noroot --nonewprivs --quiet --nogroups \
	--blacklist=/usr/bin/less \
	--blacklist=/usr/bin/more \
	--blacklist=/usr/bin/vim \
	--blacklist=/usr/bin/nano \
	--blacklist=/usr/bin/rndaddentropy \
	--blacklist=/usr/bin/sudo \
	--blacklist=/etc/passwd \
	--blacklist=/etc/sahdow \
	--blacklist=/etc/gshadow \
	--blacklist=/etc/gshadow~ \
	--blacklist=/etc/passwd~ \
	--blacklist=/etc/sahdow~ \
	--blacklist=/usr/bin/dd \
	--blacklist=/usr/bin/echo \
	--name=steam steam
